### PR TITLE
Add breaking tests for creating objects with explicit "null" values

### PR DESCRIPTION
**Pull request by EyMaddis**
It is currently impossible to create objects and pass a value as `null`, so I added a breaking test, see https://github.com/postgraphql/postgraphql/issues/584

``` graphql
createDefaultValue(input: {
    defaultValue: {
      id: 2000
      nullValue: null
    }
  }) {
    defaultValue {
      id
      nullValue // => is "defaultValue!" instead of "null"
    }
  }
```

### CODE REVIEW

**Comment by chadfurman** [comment]
Would it make sense to have a test case for when it is nullable?

**Comment by EyMaddis** [comment]
@chadfurman can you be more specific? I am not sure what you mean.

**Comment by chadfurman** [comment]
@EyMaddis I misunderstood and thought this PRdid something differently, and actually quite opposite, than it is.  The case you're testing for is "null" values on a nullable field (which is what my comment was referencing, thus the confusion):

https://github.com/graphile/graphile-build/pull/71/files#diff-c8bb689a58197b1592c6e704ad935d16R225

**Comment by benjie** [comment]
Closing in favour of #74

**Pull request closed without merging**
